version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  build_and_push:
    docker:
      - image: cimg/node:16.13 
    steps:
      - checkout

      # Set up Docker environment
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      # Build and push Docker images for each service with tag 'v1'
      - run:
          name: Build, tag, and push reverseproxy
          command: |
            docker build -t reverseproxy ./udagram-reverseproxy
            docker tag reverseproxy $DOCKERHUB_USERNAME/reverseproxy:v1
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/reverseproxy:v1

      - run:
          name: Build, tag, and push udagram-api-user
          command: |
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user $DOCKERHUB_USERNAME/udagram-api-user:v1
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-api-user:v1

      - run:
          name: Build, tag, and push udagram-api-feed
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed $DOCKERHUB_USERNAME/udagram-api-feed:v1
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:v1

      - run:
          name: Build, tag, and push udagram-frontend
          command: |
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend $DOCKERHUB_USERNAME/udagram-frontend:v1
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-frontend:v1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push