apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: 0936064271/udagram-api-user:v1
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: POSTGRES_DB
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: AWS_REGION
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: URL
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: POSTGRES_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: JWT_SECRET