apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: 0936064271/udagram-frontend:v3
        ports:
        - containerPort: 80